DROP TABLE IF EXISTS ValInt;
DROP TABLE IF EXISTS ValFloat;
DROP TABLE IF EXISTS ValString;
DROP TABLE IF EXISTS ValBlob;
DROP TABLE IF EXISTS Measurement;
DROP TABLE IF EXISTS FieldDictionary;
DROP TABLE IF EXISTS DataDictionary;
DROP TABLE IF EXISTS SoundSpeedDictionary;
