//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiamCross {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiamCross.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About company.
        /// </summary>
        public static string AboutCompany {
            get {
                return ResourceManager.GetString("AboutCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About app.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Acceleration.
        /// </summary>
        public static string Acceleration {
            get {
                return ResourceManager.GetString("Acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Additional amplification.
        /// </summary>
        public static string AdditionalAmp {
            get {
                return ResourceManager.GetString("AdditionalAmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Amplification.
        /// </summary>
        public static string Amplification {
            get {
                return ResourceManager.GetString("Amplification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Annular pressure, kgf/cm2.
        /// </summary>
        public static string AnnularPressure {
            get {
                return ResourceManager.GetString("AnnularPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Crank hole number.
        /// </summary>
        public static string ApertNumber {
            get {
                return ResourceManager.GetString("ApertNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the crank hole number!.
        /// </summary>
        public static string ApertNumberChoiceText {
            get {
                return ResourceManager.GetString("ApertNumberChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The hole number must be from 1 to 5!.
        /// </summary>
        public static string ApertNumberErrorTextDdimSiddos {
            get {
                return ResourceManager.GetString("ApertNumberErrorTextDdimSiddos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application version:.
        /// </summary>
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Atm.
        /// </summary>
        public static string AtmosphereUnits {
            get {
                return ResourceManager.GetString("AtmosphereUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attached.
        /// </summary>
        public static string Attached {
            get {
                return ResourceManager.GetString("Attached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attention.
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authentication data.
        /// </summary>
        public static string AuthentificationData {
            get {
                return ResourceManager.GetString("AuthentificationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authorization.
        /// </summary>
        public static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Balancer.
        /// </summary>
        public static string BalancedModelPump {
            get {
                return ResourceManager.GetString("BalancedModelPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bluetooth 5.
        /// </summary>
        public static string Bluetooth5 {
            get {
                return ResourceManager.GetString("Bluetooth5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bluetooth is disable.
        /// </summary>
        public static string BluetoothIsDisable {
            get {
                return ResourceManager.GetString("BluetoothIsDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Buffer pressure.
        /// </summary>
        public static string BufferPressure {
            get {
                return ResourceManager.GetString("BufferPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the buffer pressure!.
        /// </summary>
        public static string BufferPressureChoiceText {
            get {
                return ResourceManager.GetString("BufferPressureChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cluster.
        /// </summary>
        public static string Bush {
            get {
                return ResourceManager.GetString("Bush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the cluster number!.
        /// </summary>
        public static string BushChoiceText {
            get {
                return ResourceManager.GetString("BushChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status - calculation.
        /// </summary>
        public static string CalculationStatus {
            get {
                return ResourceManager.GetString("CalculationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel research.
        /// </summary>
        public static string CancelResearch {
            get {
                return ResourceManager.GetString("CancelResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chain.
        /// </summary>
        public static string ChainModelPump {
            get {
                return ResourceManager.GetString("ChainModelPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pressure sensor sensitivity.
        /// </summary>
        public static string Chdav {
            get {
                return ResourceManager.GetString("Chdav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select the table for adjusting the speed of sound or enter the speed of sound manually!.
        /// </summary>
        public static string ChoiceSpeedCorrectionTableOrInpunSpeed {
            get {
                return ResourceManager.GetString("ChoiceSpeedCorrectionTableOrInpunSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose a file.
        /// </summary>
        public static string ChooseAFile {
            get {
                return ResourceManager.GetString("ChooseAFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Piezoelectric sensor sensitivity in arbitrary units from 0 to 255.
        /// </summary>
        public static string Chpiezo {
            get {
                return ResourceManager.GetString("Chpiezo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear memory.
        /// </summary>
        public static string ClearMemory {
            get {
                return ResourceManager.GetString("ClearMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status - waiting for the valve to be pressed.
        /// </summary>
        public static string ClickStatus {
            get {
                return ResourceManager.GetString("ClickStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Comment.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter a comment!.
        /// </summary>
        public static string CommentsChoiceText {
            get {
                return ResourceManager.GetString("CommentsChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connected.
        /// </summary>
        public static string ConnectedStatus {
            get {
                return ResourceManager.GetString("ConnectedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Control panel.
        /// </summary>
        public static string ControlPanelTitle {
            get {
                return ResourceManager.GetString("ControlPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на °C.
        /// </summary>
        public static string DegCentigradeUnits {
            get {
                return ResourceManager.GetString("DegCentigradeUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete?.
        /// </summary>
        public static string DeleteQuestion {
            get {
                return ResourceManager.GetString("DeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Detached.
        /// </summary>
        public static string Detached {
            get {
                return ResourceManager.GetString("Detached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Device.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download measurements.
        /// </summary>
        public static string DownloadMeasurements {
            get {
                return ResourceManager.GetString("DownloadMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Measurement type.
        /// </summary>
        public static string DuResearchType {
            get {
                return ResourceManager.GetString("DuResearchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dynamic level.
        /// </summary>
        public static string DynamicLevel {
            get {
                return ResourceManager.GetString("DynamicLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dynamic pressure.
        /// </summary>
        public static string DynamicPressure {
            get {
                return ResourceManager.GetString("DynamicPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dynamic pressure (single).
        /// </summary>
        public static string DynamicPressureSingle {
            get {
                return ResourceManager.GetString("DynamicPressureSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dynamogram.
        /// </summary>
        public static string Dynamogram {
            get {
                return ResourceManager.GetString("Dynamogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dynamograph.
        /// </summary>
        public static string DynamographSensorType {
            get {
                return ResourceManager.GetString("DynamographSensorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Swing period, sec.
        /// </summary>
        public static string DynPeriod {
            get {
                return ResourceManager.GetString("DynPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the swing period!.
        /// </summary>
        public static string DynPeriodChoiceText {
            get {
                return ResourceManager.GetString("DynPeriodChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The swing period must be between 4 and 300,s!
        ///Pump rate is 60sec/300sec=0.2swg to 60sec/4sec=15swg!.
        /// </summary>
        public static string DynPeriodErrorTextDdimSiddos {
            get {
                return ResourceManager.GetString("DynPeriodErrorTextDdimSiddos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Echogram.
        /// </summary>
        public static string Echogram {
            get {
                return ResourceManager.GetString("Echogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Editing.
        /// </summary>
        public static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E-mail settings.
        /// </summary>
        public static string EmailSettings {
            get {
                return ResourceManager.GetString("EmailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable bluetooth?.
        /// </summary>
        public static string EnableBluetooth {
            get {
                return ResourceManager.GetString("EnableBluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the sender address!.
        /// </summary>
        public static string EnterFromAddress {
            get {
                return ResourceManager.GetString("EnterFromAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter password.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the SMTP server address.
        /// </summary>
        public static string EnterSmtpAddress {
            get {
                return ResourceManager.GetString("EnterSmtpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter destination address.
        /// </summary>
        public static string EnterToAddress {
            get {
                return ResourceManager.GetString("EnterToAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter username.
        /// </summary>
        public static string EnterUsername {
            get {
                return ResourceManager.GetString("EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export.
        /// </summary>
        public static string ExportStatus {
            get {
                return ResourceManager.GetString("ExportStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field.
        /// </summary>
        public static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field code.
        /// </summary>
        public static string FieldCode {
            get {
                return ResourceManager.GetString("FieldCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field name.
        /// </summary>
        public static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fields.
        /// </summary>
        public static string Fields {
            get {
                return ResourceManager.GetString("Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fill in all the fields!.
        /// </summary>
        public static string FillInAllTheFields {
            get {
                return ResourceManager.GetString("FillInAllTheFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Firmware:.
        /// </summary>
        public static string Firmware {
            get {
                return ResourceManager.GetString("Firmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fluid level, m.
        /// </summary>
        public static string FluidLevel {
            get {
                return ResourceManager.GetString("FluidLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Discovered devices:.
        /// </summary>
        public static string FoundDevices {
            get {
                return ResourceManager.GetString("FoundDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status - free.
        /// </summary>
        public static string FreeStatus {
            get {
                return ResourceManager.GetString("FreeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sender address.
        /// </summary>
        public static string FromAddress {
            get {
                return ResourceManager.GetString("FromAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gas discharge / inlet from a well.
        /// </summary>
        public static string GasFromWell {
            get {
                return ResourceManager.GetString("GasFromWell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Handbook.
        /// </summary>
        public static string HandbookTitle {
            get {
                return ResourceManager.GetString("HandbookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hydraulic.
        /// </summary>
        public static string HydraulicModelPump {
            get {
                return ResourceManager.GetString("HydraulicModelPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stroke length, m.
        /// </summary>
        public static string Imtravel {
            get {
                return ResourceManager.GetString("Imtravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the stroke length!.
        /// </summary>
        public static string ImtravelChoiceText {
            get {
                return ResourceManager.GetString("ImtravelChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The stroke length must be between 0.5 and 10!.
        /// </summary>
        public static string ImtravelErrorTextDdimSiddos {
            get {
                return ResourceManager.GetString("ImtravelErrorTextDdimSiddos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect data entered!.
        /// </summary>
        public static string IncorrectDataEnteredErrorText {
            get {
                return ResourceManager.GetString("IncorrectDataEnteredErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Inlet.
        /// </summary>
        public static string Inlet {
            get {
                return ResourceManager.GetString("Inlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Interval.
        /// </summary>
        public static string Interval {
            get {
                return ResourceManager.GetString("Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите интервал!.
        /// </summary>
        public static string IntervalChoiceText {
            get {
                return ResourceManager.GetString("IntervalChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Interval must be between 1 and 82800,s!.
        /// </summary>
        public static string IntervalErrorTextUmt {
            get {
                return ResourceManager.GetString("IntervalErrorTextUmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на kgs/cm2.
        /// </summary>
        public static string KGFCMUnits {
            get {
                return ResourceManager.GetString("KGFCMUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KG.
        /// </summary>
        public static string Kilograms {
            get {
                return ResourceManager.GetString("Kilograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Langepas.
        /// </summary>
        public static string Langepas {
            get {
                return ResourceManager.GetString("Langepas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Level gauge sensor.
        /// </summary>
        public static string LevelGaugeSensorType {
            get {
                return ResourceManager.GetString("LevelGaugeSensorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Location information.
        /// </summary>
        public static string LocationInfo {
            get {
                return ResourceManager.GetString("LocationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weight of the rods in the lower position, t.
        /// </summary>
        public static string LowerRodWeight {
            get {
                return ResourceManager.GetString("LowerRodWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum level at a speed of sound 341m / s.
        /// </summary>
        public static string MaxLevelAt341 {
            get {
                return ResourceManager.GetString("MaxLevelAt341", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load max., t.
        /// </summary>
        public static string MaxLoad {
            get {
                return ResourceManager.GetString("MaxLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Measurement data.
        /// </summary>
        public static string MeasurementData {
            get {
                return ResourceManager.GetString("MeasurementData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на measurements were successfully saved.
        /// </summary>
        public static string MeasurementsSavedSuccesfully {
            get {
                return ResourceManager.GetString("MeasurementsSavedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на measurements were successfully sent.
        /// </summary>
        public static string MeasurementsSentSuccesfully {
            get {
                return ResourceManager.GetString("MeasurementsSentSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status - measuring.
        /// </summary>
        public static string MeasurementStatus {
            get {
                return ResourceManager.GetString("MeasurementStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Measurements.
        /// </summary>
        public static string MeasurementsTitle {
            get {
                return ResourceManager.GetString("MeasurementsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Test type.
        /// </summary>
        public static string MeasurementType {
            get {
                return ResourceManager.GetString("MeasurementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на mV.
        /// </summary>
        public static string MilliVoltsUnits {
            get {
                return ResourceManager.GetString("MilliVoltsUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load min., t.
        /// </summary>
        public static string MinLoad {
            get {
                return ResourceManager.GetString("MinLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drive type.
        /// </summary>
        public static string ModelPump {
            get {
                return ResourceManager.GetString("ModelPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на m/s.
        /// </summary>
        public static string MSUnits {
            get {
                return ResourceManager.GetString("MSUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New field.
        /// </summary>
        public static string NewField {
            get {
                return ResourceManager.GetString("NewField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New folder.
        /// </summary>
        public static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No connection.
        /// </summary>
        public static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status - noise measuring.
        /// </summary>
        public static string NoiseStatus {
            get {
                return ResourceManager.GetString("NoiseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pressure sensor zero offset, 0.1 atm.
        /// </summary>
        public static string Noldav {
            get {
                return ResourceManager.GetString("Noldav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not.
        /// </summary>
        public static string NotButton {
            get {
                return ResourceManager.GetString("NotButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No comment.
        /// </summary>
        public static string NoСomment {
            get {
                return ResourceManager.GetString("NoСomment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of reflections.
        /// </summary>
        public static string NumberOfReflections {
            get {
                return ResourceManager.GetString("NumberOfReflections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status - preprocessing.
        /// </summary>
        public static string PreparationStatus {
            get {
                return ResourceManager.GetString("PreparationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pressure.
        /// </summary>
        public static string Pressure {
            get {
                return ResourceManager.GetString("Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pressure gauge.
        /// </summary>
        public static string PressureGauge {
            get {
                return ResourceManager.GetString("PressureGauge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на at.
        /// </summary>
        public static string PressureUnits {
            get {
                return ResourceManager.GetString("PressureUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pump speed, SPM.
        /// </summary>
        public static string PumpRate {
            get {
                return ResourceManager.GetString("PumpRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RadioFirmware:.
        /// </summary>
        public static string RadioFirmware {
            get {
                return ResourceManager.GetString("RadioFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rod diameter, m.
        /// </summary>
        public static string Rod {
            get {
                return ResourceManager.GetString("Rod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the rod diameter!.
        /// </summary>
        public static string RodChoiceText {
            get {
                return ResourceManager.GetString("RodChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The rod diameter must be from 12 to 40!.
        /// </summary>
        public static string RodErrorTextDdin2 {
            get {
                return ResourceManager.GetString("RodErrorTextDdin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saving measurements.
        /// </summary>
        public static string SavingMeasurements {
            get {
                return ResourceManager.GetString("SavingMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status - saving.
        /// </summary>
        public static string SavingStatus {
            get {
                return ResourceManager.GetString("SavingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        public static string SearchTitle {
            get {
                return ResourceManager.GetString("SearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на sec.
        /// </summary>
        public static string SecondUnits {
            get {
                return ResourceManager.GetString("SecondUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose a field!.
        /// </summary>
        public static string SelectedFieldChoiceText {
            get {
                return ResourceManager.GetString("SelectedFieldChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selected.
        /// </summary>
        public static string SelectedMeasurements {
            get {
                return ResourceManager.GetString("SelectedMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите тип исследования.
        /// </summary>
        public static string SelectedMeasurementTypeChoiceText {
            get {
                return ResourceManager.GetString("SelectedMeasurementTypeChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose drive type!.
        /// </summary>
        public static string SelectedModelPumpChoiceText {
            get {
                return ResourceManager.GetString("SelectedModelPumpChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose research type!.
        /// </summary>
        public static string SelectedReasearchTypeChoice {
            get {
                return ResourceManager.GetString("SelectedReasearchTypeChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose sound speed correction!.
        /// </summary>
        public static string SelectedSoundSpeedCorrectionChoice {
            get {
                return ResourceManager.GetString("SelectedSoundSpeedCorrectionChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send to E-mail.
        /// </summary>
        public static string SendingMeasurements {
            get {
                return ResourceManager.GetString("SendingMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Share measurement.
        /// </summary>
        public static string ShareMeasurement {
            get {
                return ResourceManager.GetString("ShareMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Department.
        /// </summary>
        public static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the department number!.
        /// </summary>
        public static string ShopChoiceText {
            get {
                return ResourceManager.GetString("ShopChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Site.
        /// </summary>
        public static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SMTP server address.
        /// </summary>
        public static string SmtpAddress {
            get {
                return ResourceManager.GetString("SmtpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sound speed.
        /// </summary>
        public static string SoundSpeed {
            get {
                return ResourceManager.GetString("SoundSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sound speed correction.
        /// </summary>
        public static string SoundSpeedCorrection {
            get {
                return ResourceManager.GetString("SoundSpeedCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start measurement.
        /// </summary>
        public static string StartMeasurement {
            get {
                return ResourceManager.GetString("StartMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Static level.
        /// </summary>
        public static string StaticLevel {
            get {
                return ResourceManager.GetString("StaticLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Static pressure.
        /// </summary>
        public static string StaticPressure {
            get {
                return ResourceManager.GetString("StaticPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Static pressure (single).
        /// </summary>
        public static string StaticPressureSingle {
            get {
                return ResourceManager.GetString("StaticPressureSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save error.
        /// </summary>
        public static string StatusSaveError {
            get {
                return ResourceManager.GetString("StatusSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tataria.
        /// </summary>
        public static string Tataria {
            get {
                return ResourceManager.GetString("Tataria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Temperature.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Temperature measurement.
        /// </summary>
        public static string TemperatureMeasurement {
            get {
                return ResourceManager.GetString("TemperatureMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The «SIAM» company has been operating since 1990, and has reached a leading position in the market of equipment and services for hydrodynamic and geological field research of wells. The company is part of the «Integra Group of Companies», which is rightfully considered the leading integrated oilfield services company in Russia and the CIS countries.
        ///Since 1990, the Tomsk Scientific Production and Implementation Society «SIAM» has been developing, producing equipment for well research. Over the years, many  [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string TextAboutCompany {
            get {
                return ResourceManager.GetString("TextAboutCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Destination address.
        /// </summary>
        public static string ToAddress {
            get {
                return ResourceManager.GetString("ToAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The weight of the rods in the upper position, t.
        /// </summary>
        public static string UpperRodWeight {
            get {
                return ResourceManager.GetString("UpperRodWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на USB state:.
        /// </summary>
        public static string USBState {
            get {
                return ResourceManager.GetString("USBState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User name.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Valve test.
        /// </summary>
        public static string ValveTest {
            get {
                return ResourceManager.GetString("ValveTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Voltage.
        /// </summary>
        public static string Voltage {
            get {
                return ResourceManager.GetString("Voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на V.
        /// </summary>
        public static string VoltsUnits {
            get {
                return ResourceManager.GetString("VoltsUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Well.
        /// </summary>
        public static string Well {
            get {
                return ResourceManager.GetString("Well", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the well!.
        /// </summary>
        public static string WellChoiceText {
            get {
                return ResourceManager.GetString("WellChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrong format or content.
        /// </summary>
        public static string WrongFormatOrContent {
            get {
                return ResourceManager.GetString("WrongFormatOrContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        public static string YesButton {
            get {
                return ResourceManager.GetString("YesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Zeroing sensor.
        /// </summary>
        public static string ZeroingSensor {
            get {
                return ResourceManager.GetString("ZeroingSensor", resourceCulture);
            }
        }
    }
}
