//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiamCross {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiamCross.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Acceleration {
            get {
                return ResourceManager.GetString("Acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите номер отверствия!.
        /// </summary>
        public static string ApertNumberChoiceText {
            get {
                return ResourceManager.GetString("ApertNumberChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер отверстия должен быть в пределе от 1 до 5!.
        /// </summary>
        public static string ApertNumberErrorTextDdimSiddos {
            get {
                return ResourceManager.GetString("ApertNumberErrorTextDdimSiddos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Balanced.
        /// </summary>
        public static string BalancedModelPump {
            get {
                return ResourceManager.GetString("BalancedModelPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите буфер давления!.
        /// </summary>
        public static string BufferPressureChoiceText {
            get {
                return ResourceManager.GetString("BufferPressureChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите номер куста!.
        /// </summary>
        public static string BushChoiceText {
            get {
                return ResourceManager.GetString("BushChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расчет.
        /// </summary>
        public static string CalculationStatus {
            get {
                return ResourceManager.GetString("CalculationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chain.
        /// </summary>
        public static string ChainModelPump {
            get {
                return ResourceManager.GetString("ChainModelPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите комментарий!.
        /// </summary>
        public static string CommentsChoiceText {
            get {
                return ResourceManager.GetString("CommentsChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string DegCentigradeUnits {
            get {
                return ResourceManager.GetString("DegCentigradeUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dynamogram.
        /// </summary>
        public static string Dynamogram {
            get {
                return ResourceManager.GetString("Dynamogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dynamograph.
        /// </summary>
        public static string DynamographSensorType {
            get {
                return ResourceManager.GetString("DynamographSensorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите период качания!.
        /// </summary>
        public static string DynPeriodChoiceText {
            get {
                return ResourceManager.GetString("DynPeriodChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Период качания должен быть в пределе от 4 до 300!.
        /// </summary>
        public static string DynPeriodErrorTextDdimSiddos {
            get {
                return ResourceManager.GetString("DynPeriodErrorTextDdimSiddos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт.
        /// </summary>
        public static string ExportStatus {
            get {
                return ResourceManager.GetString("ExportStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Found devices:.
        /// </summary>
        public static string FoundDevices {
            get {
                return ResourceManager.GetString("FoundDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Датчик свободен.
        /// </summary>
        public static string FreeStatus {
            get {
                return ResourceManager.GetString("FreeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hydraulic.
        /// </summary>
        public static string HydraulicModelPump {
            get {
                return ResourceManager.GetString("HydraulicModelPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите длину хода!.
        /// </summary>
        public static string ImtravelChoiceText {
            get {
                return ResourceManager.GetString("ImtravelChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Длина хода должна быть в пределе от 0,5 до 10!.
        /// </summary>
        public static string ImtravelErrorTextDdimSiddos {
            get {
                return ResourceManager.GetString("ImtravelErrorTextDdimSiddos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect data entered!.
        /// </summary>
        public static string IncorrectDataEnteredErrorText {
            get {
                return ResourceManager.GetString("IncorrectDataEnteredErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Kilograms {
            get {
                return ResourceManager.GetString("Kilograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Измерение.
        /// </summary>
        public static string MeasurementStatus {
            get {
                return ResourceManager.GetString("MeasurementStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string MilliVoltsUnits {
            get {
                return ResourceManager.GetString("MilliVoltsUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подготовка.
        /// </summary>
        public static string PreparationStatus {
            get {
                return ResourceManager.GetString("PreparationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Введите диаметр штока!&quot;.
        /// </summary>
        public static string RodChoiceText {
            get {
                return ResourceManager.GetString("RodChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Диаметр штока должен быть в пределе от 12 до 40!.
        /// </summary>
        public static string RodErrorTextDdin2 {
            get {
                return ResourceManager.GetString("RodErrorTextDdin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранение.
        /// </summary>
        public static string SavingStatus {
            get {
                return ResourceManager.GetString("SavingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите месторождение!.
        /// </summary>
        public static string SelectedFieldChoiceText {
            get {
                return ResourceManager.GetString("SelectedFieldChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите тип привода!.
        /// </summary>
        public static string SelectedModelPumpChoiceText {
            get {
                return ResourceManager.GetString("SelectedModelPumpChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Share measurement.
        /// </summary>
        public static string ShareMeasurement {
            get {
                return ResourceManager.GetString("ShareMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите номер цеха!.
        /// </summary>
        public static string ShopChoiceText {
            get {
                return ResourceManager.GetString("ShopChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Valve test.
        /// </summary>
        public static string ValveTest {
            get {
                return ResourceManager.GetString("ValveTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string Voltage {
            get {
                return ResourceManager.GetString("Voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string VoltsUnits {
            get {
                return ResourceManager.GetString("VoltsUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите скважину!.
        /// </summary>
        public static string WellChoiceText {
            get {
                return ResourceManager.GetString("WellChoiceText", resourceCulture);
            }
        }
    }
}
