//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiamCross {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiamCross.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About company.
        /// </summary>
        public static string AboutCompany {
            get {
                return ResourceManager.GetString("AboutCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на liquid level observed during pumping.
        /// </summary>
        public static string AboutDynamicLevel {
            get {
                return ResourceManager.GetString("AboutDynamicLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на single measurement.
        /// </summary>
        public static string AboutDynamics {
            get {
                return ResourceManager.GetString("AboutDynamics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на periodic measurement.
        /// </summary>
        public static string AboutDynamics_period {
            get {
                return ResourceManager.GetString("AboutDynamics_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на level drop curve.
        /// </summary>
        public static string AboutLDC {
            get {
                return ResourceManager.GetString("AboutLDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на level recovery curve.
        /// </summary>
        public static string AboutLRC {
            get {
                return ResourceManager.GetString("AboutLRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на pressure automatic recording.
        /// </summary>
        public static string AboutPAR {
            get {
                return ResourceManager.GetString("AboutPAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Setting parameters, starting and stopping the survey.
        /// </summary>
        public static string AboutResearches {
            get {
                return ResourceManager.GetString("AboutResearches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на single measurement.
        /// </summary>
        public static string AboutStatic {
            get {
                return ResourceManager.GetString("AboutStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на periodic measurement.
        /// </summary>
        public static string AboutStatic_period {
            get {
                return ResourceManager.GetString("AboutStatic_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на liquid level in a calm state.
        /// </summary>
        public static string AboutStaticLevel {
            get {
                return ResourceManager.GetString("AboutStaticLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Getting one or more survay from the device&apos;s memory.
        /// </summary>
        public static string AboutStorage {
            get {
                return ResourceManager.GetString("AboutStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About app.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Acceleration.
        /// </summary>
        public static string Acceleration {
            get {
                return ResourceManager.GetString("Acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add a device (click to confirm).
        /// </summary>
        public static string AddDevice {
            get {
                return ResourceManager.GetString("AddDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Additional amplification.
        /// </summary>
        public static string AdditionalAmp {
            get {
                return ResourceManager.GetString("AdditionalAmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Additional gain.
        /// </summary>
        public static string AdditionalGain {
            get {
                return ResourceManager.GetString("AdditionalGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Additionally.
        /// </summary>
        public static string Additionally {
            get {
                return ResourceManager.GetString("Additionally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Amplification.
        /// </summary>
        public static string Amplification {
            get {
                return ResourceManager.GetString("Amplification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Annular pressure, kgf/cm2.
        /// </summary>
        public static string AnnularPressure {
            get {
                return ResourceManager.GetString("AnnularPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Crank hole number.
        /// </summary>
        public static string ApertNumber {
            get {
                return ResourceManager.GetString("ApertNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the crank hole number!.
        /// </summary>
        public static string ApertNumberChoiceText {
            get {
                return ResourceManager.GetString("ApertNumberChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The hole number must be from 1 to 5!.
        /// </summary>
        public static string ApertNumberErrorTextDdimSiddos {
            get {
                return ResourceManager.GetString("ApertNumberErrorTextDdimSiddos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changes in the version.
        /// </summary>
        public static string AppChanges {
            get {
                return ResourceManager.GetString("AppChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application version:.
        /// </summary>
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ascending by ID.
        /// </summary>
        public static string AscendingByID {
            get {
                return ResourceManager.GetString("AscendingByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ascending by name.
        /// </summary>
        public static string AscendingByName {
            get {
                return ResourceManager.GetString("AscendingByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Atm.
        /// </summary>
        public static string AtmosphereUnits {
            get {
                return ResourceManager.GetString("AtmosphereUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attached.
        /// </summary>
        public static string Attached {
            get {
                return ResourceManager.GetString("Attached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attention.
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authentication data.
        /// </summary>
        public static string AuthentificationData {
            get {
                return ResourceManager.GetString("AuthentificationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authorization.
        /// </summary>
        public static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на automatic.
        /// </summary>
        public static string Automatic {
            get {
                return ResourceManager.GetString("Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Automatic valve.
        /// </summary>
        public static string AutomaticValve {
            get {
                return ResourceManager.GetString("AutomaticValve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Balancer.
        /// </summary>
        public static string BalancedModelPump {
            get {
                return ResourceManager.GetString("BalancedModelPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Begin.
        /// </summary>
        public static string Begin {
            get {
                return ResourceManager.GetString("Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bluetooth 5.
        /// </summary>
        public static string Bluetooth5 {
            get {
                return ResourceManager.GetString("Bluetooth5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bluetooth is disable.
        /// </summary>
        public static string BluetoothIsDisable {
            get {
                return ResourceManager.GetString("BluetoothIsDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Buffer pressure.
        /// </summary>
        public static string BufferPressure {
            get {
                return ResourceManager.GetString("BufferPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the buffer pressure!.
        /// </summary>
        public static string BufferPressureChoiceText {
            get {
                return ResourceManager.GetString("BufferPressureChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cluster.
        /// </summary>
        public static string Bush {
            get {
                return ResourceManager.GetString("Bush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the cluster number!.
        /// </summary>
        public static string BushChoiceText {
            get {
                return ResourceManager.GetString("BushChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By default.
        /// </summary>
        public static string ByDefault {
            get {
                return ResourceManager.GetString("ByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel research.
        /// </summary>
        public static string CancelResearch {
            get {
                return ResourceManager.GetString("CancelResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chain.
        /// </summary>
        public static string ChainModelPump {
            get {
                return ResourceManager.GetString("ChainModelPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на For the changes to take effect, restart the application..
        /// </summary>
        public static string ChangingLanguage {
            get {
                return ResourceManager.GetString("ChangingLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pressure sensor sensitivity.
        /// </summary>
        public static string Chdav {
            get {
                return ResourceManager.GetString("Chdav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select the table for adjusting the speed of sound or enter the speed of sound manually!.
        /// </summary>
        public static string ChoiceSpeedCorrectionTableOrInpunSpeed {
            get {
                return ResourceManager.GetString("ChoiceSpeedCorrectionTableOrInpunSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose a file.
        /// </summary>
        public static string ChooseAFile {
            get {
                return ResourceManager.GetString("ChooseAFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Piezoelectric sensor sensitivity in arbitrary units from 0 to 255.
        /// </summary>
        public static string Chpiezo {
            get {
                return ResourceManager.GetString("Chpiezo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clearing the memory.
        /// </summary>
        public static string ClearingMemory {
            get {
                return ResourceManager.GetString("ClearingMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear memory.
        /// </summary>
        public static string ClearMemory {
            get {
                return ResourceManager.GetString("ClearMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close app?.
        /// </summary>
        public static string CloseApp {
            get {
                return ResourceManager.GetString("CloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Comment.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter a comment!.
        /// </summary>
        public static string CommentsChoiceText {
            get {
                return ResourceManager.GetString("CommentsChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Complete.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connected.
        /// </summary>
        public static string ConnectedStatus {
            get {
                return ResourceManager.GetString("ConnectedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection type.
        /// </summary>
        public static string ConnectionType {
            get {
                return ResourceManager.GetString("ConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Control panel.
        /// </summary>
        public static string ControlPanelTitle {
            get {
                return ResourceManager.GetString("ControlPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на °C.
        /// </summary>
        public static string DegCentigradeUnits {
            get {
                return ResourceManager.GetString("DegCentigradeUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete?.
        /// </summary>
        public static string DeleteQuestion {
            get {
                return ResourceManager.GetString("DeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Descending by ID.
        /// </summary>
        public static string DescendingByID {
            get {
                return ResourceManager.GetString("DescendingByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Descending by name.
        /// </summary>
        public static string DescendingByName {
            get {
                return ResourceManager.GetString("DescendingByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Detached.
        /// </summary>
        public static string Detached {
            get {
                return ResourceManager.GetString("Detached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на determining time.
        /// </summary>
        public static string DeterminingTime {
            get {
                return ResourceManager.GetString("DeterminingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Device.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Device time.
        /// </summary>
        public static string DeviceTime {
            get {
                return ResourceManager.GetString("DeviceTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connect.
        /// </summary>
        public static string DoConnect {
            get {
                return ResourceManager.GetString("DoConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string DoDelete {
            get {
                return ResourceManager.GetString("DoDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export.
        /// </summary>
        public static string DoExport {
            get {
                return ResourceManager.GetString("DoExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import.
        /// </summary>
        public static string DoImport {
            get {
                return ResourceManager.GetString("DoImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load.
        /// </summary>
        public static string DoLoad {
            get {
                return ResourceManager.GetString("DoLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на survey.
        /// </summary>
        public static string DopSurvey {
            get {
                return ResourceManager.GetString("DopSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string DoSave {
            get {
                return ResourceManager.GetString("DoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на downloading.
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download measurements.
        /// </summary>
        public static string DownloadMeasurements {
            get {
                return ResourceManager.GetString("DownloadMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dynamic level.
        /// </summary>
        public static string DynamicLevel {
            get {
                return ResourceManager.GetString("DynamicLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dynamic pressure.
        /// </summary>
        public static string DynamicPressure {
            get {
                return ResourceManager.GetString("DynamicPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dynamic pressure (single).
        /// </summary>
        public static string DynamicPressureSingle {
            get {
                return ResourceManager.GetString("DynamicPressureSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dynamics.
        /// </summary>
        public static string Dynamics {
            get {
                return ResourceManager.GetString("Dynamics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dynamics(period).
        /// </summary>
        public static string Dynamics_period {
            get {
                return ResourceManager.GetString("Dynamics_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dynamogram.
        /// </summary>
        public static string Dynamogram {
            get {
                return ResourceManager.GetString("Dynamogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на dynamograph.
        /// </summary>
        public static string Dynamograph {
            get {
                return ResourceManager.GetString("Dynamograph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dynamograph.
        /// </summary>
        public static string DynamographSensorType {
            get {
                return ResourceManager.GetString("DynamographSensorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Swing period, sec.
        /// </summary>
        public static string DynPeriod {
            get {
                return ResourceManager.GetString("DynPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the swing period!.
        /// </summary>
        public static string DynPeriodChoiceText {
            get {
                return ResourceManager.GetString("DynPeriodChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The swing period must be between 4 and 300,s!
        ///Pump rate is 60sec/300sec=0.2swg to 60sec/4sec=15swg!.
        /// </summary>
        public static string DynPeriodErrorTextDdimSiddos {
            get {
                return ResourceManager.GetString("DynPeriodErrorTextDdimSiddos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Echogram.
        /// </summary>
        public static string Echogram {
            get {
                return ResourceManager.GetString("Echogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Editing.
        /// </summary>
        public static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E-mail settings.
        /// </summary>
        public static string EmailSettings {
            get {
                return ResourceManager.GetString("EmailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на empty.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable bluetooth?.
        /// </summary>
        public static string EnableBluetooth {
            get {
                return ResourceManager.GetString("EnableBluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the sender address!.
        /// </summary>
        public static string EnterFromAddress {
            get {
                return ResourceManager.GetString("EnterFromAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter password.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the SMTP server address.
        /// </summary>
        public static string EnterSmtpAddress {
            get {
                return ResourceManager.GetString("EnterSmtpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter destination address.
        /// </summary>
        public static string EnterToAddress {
            get {
                return ResourceManager.GetString("EnterToAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter username.
        /// </summary>
        public static string EnterUsername {
            get {
                return ResourceManager.GetString("EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The name is empty or such a file already exists.
        /// </summary>
        public static string ErrorNameFile {
            get {
                return ResourceManager.GetString("ErrorNameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Execute PAR at a level less than 50 m..
        /// </summary>
        public static string ExecutePAR {
            get {
                return ResourceManager.GetString("ExecutePAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Execution time 0.2/0.05.
        /// </summary>
        public static string ExecutionTime {
            get {
                return ResourceManager.GetString("ExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export.
        /// </summary>
        public static string ExportStatus {
            get {
                return ResourceManager.GetString("ExportStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на External.
        /// </summary>
        public static string External {
            get {
                return ResourceManager.GetString("External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Factory settings.
        /// </summary>
        public static string FactorySettings {
            get {
                return ResourceManager.GetString("FactorySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на failed to connect to the device.
        /// </summary>
        public static string Failed_connect {
            get {
                return ResourceManager.GetString("Failed_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field.
        /// </summary>
        public static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fields.
        /// </summary>
        public static string Fields {
            get {
                return ResourceManager.GetString("Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The file is saved.
        /// </summary>
        public static string FileSaved {
            get {
                return ResourceManager.GetString("FileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fill in all the fields!.
        /// </summary>
        public static string FillInAllTheFields {
            get {
                return ResourceManager.GetString("FillInAllTheFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Firmware:.
        /// </summary>
        public static string Firmware {
            get {
                return ResourceManager.GetString("Firmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fluid level, m.
        /// </summary>
        public static string FluidLevel {
            get {
                return ResourceManager.GetString("FluidLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Discovered devices:.
        /// </summary>
        public static string FoundDevices {
            get {
                return ResourceManager.GetString("FoundDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Free memory.
        /// </summary>
        public static string FreeMemory {
            get {
                return ResourceManager.GetString("FreeMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на from.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gas direction: in / out.
        /// </summary>
        public static string GasDirection {
            get {
                return ResourceManager.GetString("GasDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gas discharge / inlet from a well.
        /// </summary>
        public static string GasFromWell {
            get {
                return ResourceManager.GetString("GasFromWell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Handbook.
        /// </summary>
        public static string HandbookTitle {
            get {
                return ResourceManager.GetString("HandbookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hydraulic.
        /// </summary>
        public static string HydraulicModelPump {
            get {
                return ResourceManager.GetString("HydraulicModelPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stroke length, m.
        /// </summary>
        public static string Imtravel {
            get {
                return ResourceManager.GetString("Imtravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the stroke length!.
        /// </summary>
        public static string ImtravelChoiceText {
            get {
                return ResourceManager.GetString("ImtravelChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The stroke length must be between 0.5 and 10!.
        /// </summary>
        public static string ImtravelErrorTextDdimSiddos {
            get {
                return ResourceManager.GetString("ImtravelErrorTextDdimSiddos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect data entered!.
        /// </summary>
        public static string IncorrectDataEnteredErrorText {
            get {
                return ResourceManager.GetString("IncorrectDataEnteredErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на initialization.
        /// </summary>
        public static string Init {
            get {
                return ResourceManager.GetString("Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на initialization.
        /// </summary>
        public static string Initialization {
            get {
                return ResourceManager.GetString("Initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Initial survey.
        /// </summary>
        public static string InitialSurvey {
            get {
                return ResourceManager.GetString("InitialSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Inlet.
        /// </summary>
        public static string Inlet {
            get {
                return ResourceManager.GetString("Inlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Internal.
        /// </summary>
        public static string Internal {
            get {
                return ResourceManager.GetString("Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на intertraversal.
        /// </summary>
        public static string Intertraversal {
            get {
                return ResourceManager.GetString("Intertraversal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Interval.
        /// </summary>
        public static string Interval {
            get {
                return ResourceManager.GetString("Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Imtravel choice text.
        /// </summary>
        public static string IntervalChoiceText {
            get {
                return ResourceManager.GetString("IntervalChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Interval must be between 1 and 82800,s!.
        /// </summary>
        public static string IntervalErrorTextUmt {
            get {
                return ResourceManager.GetString("IntervalErrorTextUmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на kgs/cm2.
        /// </summary>
        public static string KGFCMUnits {
            get {
                return ResourceManager.GetString("KGFCMUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KG.
        /// </summary>
        public static string Kilograms {
            get {
                return ResourceManager.GetString("Kilograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Langepas.
        /// </summary>
        public static string Langepas {
            get {
                return ResourceManager.GetString("Langepas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LDC.
        /// </summary>
        public static string LDC {
            get {
                return ResourceManager.GetString("LDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Level gauge sensor.
        /// </summary>
        public static string LevelGaugeSensorType {
            get {
                return ResourceManager.GetString("LevelGaugeSensorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на level meter.
        /// </summary>
        public static string Levelmeter {
            get {
                return ResourceManager.GetString("Levelmeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Level sensor.
        /// </summary>
        public static string LevelSensor {
            get {
                return ResourceManager.GetString("LevelSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading location.
        /// </summary>
        public static string LoadingLocation {
            get {
                return ResourceManager.GetString("LoadingLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Location information.
        /// </summary>
        public static string LocationInfo {
            get {
                return ResourceManager.GetString("LocationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weight of the rods in the lower position, t.
        /// </summary>
        public static string LowerRodWeight {
            get {
                return ResourceManager.GetString("LowerRodWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LRC.
        /// </summary>
        public static string LRC {
            get {
                return ResourceManager.GetString("LRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на manometr.
        /// </summary>
        public static string Manometr {
            get {
                return ResourceManager.GetString("Manometr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на manual.
        /// </summary>
        public static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Depth measurement up to 6000m.
        /// </summary>
        public static string MaxDepth6000 {
            get {
                return ResourceManager.GetString("MaxDepth6000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The maximum depth is 3000m./6000m..
        /// </summary>
        public static string MaximumDepth {
            get {
                return ResourceManager.GetString("MaximumDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum level at a speed of sound 341m / s.
        /// </summary>
        public static string MaxLevelAt341 {
            get {
                return ResourceManager.GetString("MaxLevelAt341", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load max., t.
        /// </summary>
        public static string MaxLoad {
            get {
                return ResourceManager.GetString("MaxLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Meaning.
        /// </summary>
        public static string Meaning {
            get {
                return ResourceManager.GetString("Meaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на measurements.
        /// </summary>
        public static string Measurements {
            get {
                return ResourceManager.GetString("Measurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на measurements were successfully saved.
        /// </summary>
        public static string MeasurementsSavedSuccesfully {
            get {
                return ResourceManager.GetString("MeasurementsSavedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на measurements were successfully sent.
        /// </summary>
        public static string MeasurementsSentSuccesfully {
            get {
                return ResourceManager.GetString("MeasurementsSentSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на measuring.
        /// </summary>
        public static string Measuring {
            get {
                return ResourceManager.GetString("Measuring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на mV.
        /// </summary>
        public static string MilliVoltsUnits {
            get {
                return ResourceManager.GetString("MilliVoltsUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load min., t.
        /// </summary>
        public static string MinLoad {
            get {
                return ResourceManager.GetString("MinLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drive type.
        /// </summary>
        public static string ModelPump {
            get {
                return ResourceManager.GetString("ModelPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на m/s.
        /// </summary>
        public static string MSUnits {
            get {
                return ResourceManager.GetString("MSUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New field.
        /// </summary>
        public static string NewField {
            get {
                return ResourceManager.GetString("NewField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New folder.
        /// </summary>
        public static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No connection.
        /// </summary>
        public static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pressure sensor zero offset, 0.1 atm.
        /// </summary>
        public static string Noldav {
            get {
                return ResourceManager.GetString("Noldav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not.
        /// </summary>
        public static string NotButton {
            get {
                return ResourceManager.GetString("NotButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на will be synchronized at startup.
        /// </summary>
        public static string NotificationTime {
            get {
                return ResourceManager.GetString("NotificationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на not reading.
        /// </summary>
        public static string NotReading {
            get {
                return ResourceManager.GetString("NotReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No comment.
        /// </summary>
        public static string NoСomment {
            get {
                return ResourceManager.GetString("NoСomment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of measurements.
        /// </summary>
        public static string NumberOfMeasurements {
            get {
                return ResourceManager.GetString("NumberOfMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of reflections.
        /// </summary>
        public static string NumberOfReflections {
            get {
                return ResourceManager.GetString("NumberOfReflections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на overhead.
        /// </summary>
        public static string Overhead {
            get {
                return ResourceManager.GetString("Overhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PAR.
        /// </summary>
        public static string PAR {
            get {
                return ResourceManager.GetString("PAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на the parameters are not reading, update the parameters.
        /// </summary>
        public static string ParametersNotReading {
            get {
                return ResourceManager.GetString("ParametersNotReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Period in minunes.
        /// </summary>
        public static string Period_m {
            get {
                return ResourceManager.GetString("Period_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Period in seconds.
        /// </summary>
        public static string Period_s {
            get {
                return ResourceManager.GetString("Period_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Piezo sensor.
        /// </summary>
        public static string PiezoSensor {
            get {
                return ResourceManager.GetString("PiezoSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status - preprocessing.
        /// </summary>
        public static string PreparationStatus {
            get {
                return ResourceManager.GetString("PreparationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pressure.
        /// </summary>
        public static string Pressure {
            get {
                return ResourceManager.GetString("Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pressure gauge.
        /// </summary>
        public static string PressureGauge {
            get {
                return ResourceManager.GetString("PressureGauge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pressure sensor.
        /// </summary>
        public static string PressureSensor {
            get {
                return ResourceManager.GetString("PressureSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на pressure thermal compensation coefficients.
        /// </summary>
        public static string PressureThermalCompensationCoefficients {
            get {
                return ResourceManager.GetString("PressureThermalCompensationCoefficients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на at.
        /// </summary>
        public static string PressureUnits {
            get {
                return ResourceManager.GetString("PressureUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Probe temp..
        /// </summary>
        public static string ProbeTemperature {
            get {
                return ResourceManager.GetString("ProbeTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Protocol.
        /// </summary>
        public static string Protocol {
            get {
                return ResourceManager.GetString("Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Protocol type.
        /// </summary>
        public static string ProtocolType {
            get {
                return ResourceManager.GetString("ProtocolType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pump depth.
        /// </summary>
        public static string PumpDepth {
            get {
                return ResourceManager.GetString("PumpDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pump speed, SPM.
        /// </summary>
        public static string PumpRate {
            get {
                return ResourceManager.GetString("PumpRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RadioFirmware:.
        /// </summary>
        public static string RadioFirmware {
            get {
                return ResourceManager.GetString("RadioFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Read all.
        /// </summary>
        public static string ReadAll {
            get {
                return ResourceManager.GetString("ReadAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reading.
        /// </summary>
        public static string Reading {
            get {
                return ResourceManager.GetString("Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на reading current information.
        /// </summary>
        public static string ReadingCurrentInformation {
            get {
                return ResourceManager.GetString("ReadingCurrentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на reading header.
        /// </summary>
        public static string ReadingHeader {
            get {
                return ResourceManager.GetString("ReadingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на reading information.
        /// </summary>
        public static string ReadingInformation {
            get {
                return ResourceManager.GetString("ReadingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на reading memory information.
        /// </summary>
        public static string ReadingMemoryInformation {
            get {
                return ResourceManager.GetString("ReadingMemoryInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на reading the current memory status.
        /// </summary>
        public static string ReadingMemoryStatus {
            get {
                return ResourceManager.GetString("ReadingMemoryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на reading the number of survey.
        /// </summary>
        public static string ReadingNumberSurvey {
            get {
                return ResourceManager.GetString("ReadingNumberSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на reading parameters.
        /// </summary>
        public static string ReadingParameters {
            get {
                return ResourceManager.GetString("ReadingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на reading state.
        /// </summary>
        public static string ReadingState {
            get {
                return ResourceManager.GetString("ReadingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на reading the status.
        /// </summary>
        public static string ReadingStatus {
            get {
                return ResourceManager.GetString("ReadingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reading survey.
        /// </summary>
        public static string ReadingSurvey {
            get {
                return ResourceManager.GetString("ReadingSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на reading survey information.
        /// </summary>
        public static string ReadingSurveyInformation {
            get {
                return ResourceManager.GetString("ReadingSurveyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на reading the type of survey.
        /// </summary>
        public static string ReadingSurveyType {
            get {
                return ResourceManager.GetString("ReadingSurveyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на reading the time.
        /// </summary>
        public static string ReadingTime {
            get {
                return ResourceManager.GetString("ReadingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на recording.
        /// </summary>
        public static string Recording {
            get {
                return ResourceManager.GetString("Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на recording load and movement.
        /// </summary>
        public static string RecordingLoadAndMovement {
            get {
                return ResourceManager.GetString("RecordingLoadAndMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на recording parameters.
        /// </summary>
        public static string RecordingParameters {
            get {
                return ResourceManager.GetString("RecordingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recording of survey parameters.
        /// </summary>
        public static string RecordingSurveyParameters {
            get {
                return ResourceManager.GetString("RecordingSurveyParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resistance.
        /// </summary>
        public static string Resistance {
            get {
                return ResourceManager.GetString("Resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rod diameter, m.
        /// </summary>
        public static string Rod {
            get {
                return ResourceManager.GetString("Rod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the rod diameter!.
        /// </summary>
        public static string RodChoiceText {
            get {
                return ResourceManager.GetString("RodChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The rod diameter must be from 12 to 40!.
        /// </summary>
        public static string RodErrorTextDdin2 {
            get {
                return ResourceManager.GetString("RodErrorTextDdin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save in the device.
        /// </summary>
        public static string SaveInDevice {
            get {
                return ResourceManager.GetString("SaveInDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saving the location.
        /// </summary>
        public static string SavingLocation {
            get {
                return ResourceManager.GetString("SavingLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saving measurements.
        /// </summary>
        public static string SavingMeasurements {
            get {
                return ResourceManager.GetString("SavingMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Schedule level measurement.
        /// </summary>
        public static string ScheduleLevelMeasurement {
            get {
                return ResourceManager.GetString("ScheduleLevelMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Schedule PAR.
        /// </summary>
        public static string SchedulePAR {
            get {
                return ResourceManager.GetString("SchedulePAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        public static string SearchTitle {
            get {
                return ResourceManager.GetString("SearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на sec.
        /// </summary>
        public static string SecondUnits {
            get {
                return ResourceManager.GetString("SecondUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose a field!.
        /// </summary>
        public static string SelectedFieldChoiceText {
            get {
                return ResourceManager.GetString("SelectedFieldChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selected.
        /// </summary>
        public static string SelectedMeasurements {
            get {
                return ResourceManager.GetString("SelectedMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose drive type!.
        /// </summary>
        public static string SelectedModelPumpChoiceText {
            get {
                return ResourceManager.GetString("SelectedModelPumpChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose research type!.
        /// </summary>
        public static string SelectedReasearchTypeChoice {
            get {
                return ResourceManager.GetString("SelectedReasearchTypeChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose sound speed correction!.
        /// </summary>
        public static string SelectedSoundSpeedCorrectionChoice {
            get {
                return ResourceManager.GetString("SelectedSoundSpeedCorrectionChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sender address.
        /// </summary>
        public static string SenderAddress {
            get {
                return ResourceManager.GetString("SenderAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sender name.
        /// </summary>
        public static string SenderName {
            get {
                return ResourceManager.GetString("SenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send to E-mail.
        /// </summary>
        public static string SendingMeasurements {
            get {
                return ResourceManager.GetString("SendingMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sensitivity.
        /// </summary>
        public static string Sensitivity {
            get {
                return ResourceManager.GetString("Sensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Service mode.
        /// </summary>
        public static string ServiceMode {
            get {
                return ResourceManager.GetString("ServiceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Share measurement.
        /// </summary>
        public static string ShareMeasurement {
            get {
                return ResourceManager.GetString("ShareMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Department.
        /// </summary>
        public static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the department number!.
        /// </summary>
        public static string ShopChoiceText {
            get {
                return ResourceManager.GetString("ShopChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show the reading.
        /// </summary>
        public static string ShowReading {
            get {
                return ResourceManager.GetString("ShowReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Site.
        /// </summary>
        public static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SMTP server address.
        /// </summary>
        public static string SmtpAddress {
            get {
                return ResourceManager.GetString("SmtpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sorting.
        /// </summary>
        public static string Sorting {
            get {
                return ResourceManager.GetString("Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sound speed.
        /// </summary>
        public static string SoundSpeed {
            get {
                return ResourceManager.GetString("SoundSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sound speed correction.
        /// </summary>
        public static string SoundSpeedCorrection {
            get {
                return ResourceManager.GetString("SoundSpeedCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на start.
        /// </summary>
        public static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start measurement.
        /// </summary>
        public static string StartMeasurement {
            get {
                return ResourceManager.GetString("StartMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start.
        /// </summary>
        public static string Startup {
            get {
                return ResourceManager.GetString("Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на calculation.
        /// </summary>
        public static string Stat_Calc {
            get {
                return ResourceManager.GetString("Stat_Calc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на waiting for the valve to be pressed.
        /// </summary>
        public static string Stat_ClickWait {
            get {
                return ResourceManager.GetString("Stat_ClickWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на complete.
        /// </summary>
        public static string Stat_Complete {
            get {
                return ResourceManager.GetString("Stat_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на error.
        /// </summary>
        public static string Stat_Error {
            get {
                return ResourceManager.GetString("Stat_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на free.
        /// </summary>
        public static string Stat_Free {
            get {
                return ResourceManager.GetString("Stat_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на measuring.
        /// </summary>
        public static string Stat_Meas {
            get {
                return ResourceManager.GetString("Stat_Meas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на noise measuring.
        /// </summary>
        public static string Stat_NoiseMeas {
            get {
                return ResourceManager.GetString("Stat_NoiseMeas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на auto-valve: preparation.
        /// </summary>
        public static string Stat_ValvePreparation {
            get {
                return ResourceManager.GetString("Stat_ValvePreparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на connected.
        /// </summary>
        public static string StatConn_Connected {
            get {
                return ResourceManager.GetString("StatConn_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на disconnected.
        /// </summary>
        public static string StatConn_Disconnected {
            get {
                return ResourceManager.GetString("StatConn_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на connecting.
        /// </summary>
        public static string StatConn_PendingConnect {
            get {
                return ResourceManager.GetString("StatConn_PendingConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на disconnecting.
        /// </summary>
        public static string StatConn_PendingDisconnect {
            get {
                return ResourceManager.GetString("StatConn_PendingDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Static.
        /// </summary>
        public static string Static {
            get {
                return ResourceManager.GetString("Static", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Static(period).
        /// </summary>
        public static string Static_period {
            get {
                return ResourceManager.GetString("Static_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Static level.
        /// </summary>
        public static string StaticLevel {
            get {
                return ResourceManager.GetString("StaticLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Static pressure.
        /// </summary>
        public static string StaticPressure {
            get {
                return ResourceManager.GetString("StaticPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Static pressure (single).
        /// </summary>
        public static string StaticPressureSingle {
            get {
                return ResourceManager.GetString("StaticPressureSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status Update.
        /// </summary>
        public static string StatusUpdate {
            get {
                return ResourceManager.GetString("StatusUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Storage.
        /// </summary>
        public static string Storage {
            get {
                return ResourceManager.GetString("Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Storage polling.
        /// </summary>
        public static string StoragePolling {
            get {
                return ResourceManager.GetString("StoragePolling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Successfully.
        /// </summary>
        public static string Successfully {
            get {
                return ResourceManager.GetString("Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на survey.
        /// </summary>
        public static string Survey {
            get {
                return ResourceManager.GetString("Survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Survey of measurement parameters.
        /// </summary>
        public static string Survey_parameters {
            get {
                return ResourceManager.GetString("Survey_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Survey.
        /// </summary>
        public static string Survey1 {
            get {
                return ResourceManager.GetString("Survey1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data.
        /// </summary>
        public static string SurveyData {
            get {
                return ResourceManager.GetString("SurveyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Survey quantity.
        /// </summary>
        public static string SurveyQuantity {
            get {
                return ResourceManager.GetString("SurveyQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Surveys.
        /// </summary>
        public static string Surveys {
            get {
                return ResourceManager.GetString("Surveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Survey schedule.
        /// </summary>
        public static string SurveySchedule {
            get {
                return ResourceManager.GetString("SurveySchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Survey type.
        /// </summary>
        public static string SurveyType {
            get {
                return ResourceManager.GetString("SurveyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Survey with echograms.
        /// </summary>
        public static string SurveyWithEchograms {
            get {
                return ResourceManager.GetString("SurveyWithEchograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Survey without echograms.
        /// </summary>
        public static string SurveyWithoutEchograms {
            get {
                return ResourceManager.GetString("SurveyWithoutEchograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Table.
        /// </summary>
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tataria.
        /// </summary>
        public static string Tataria {
            get {
                return ResourceManager.GetString("Tataria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Temperature.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Temperature measurement.
        /// </summary>
        public static string TemperatureMeasurement {
            get {
                return ResourceManager.GetString("TemperatureMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Temperature sensors.
        /// </summary>
        public static string TemperatureSensors {
            get {
                return ResourceManager.GetString("TemperatureSensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Software «SIAM SERVICE» is a «SIAM» software package designed for storing, transmitting, processing and interpreting data obtained during well testing via Bluetooth wireless data transmission from portable devices (dynamographs / level gauges)..
        /// </summary>
        public static string TextAboutApp {
            get {
                return ResourceManager.GetString("TextAboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The «SIAM» company has been operating since 1990, and has reached a leading position in the market of equipment and services for hydrodynamic and geological field research of wells. The company is part of the «Integra Group of Companies», which is rightfully considered the leading integrated oilfield services company in Russia and the CIS countries.
        ///Since 1990, the Tomsk Scientific Production and Implementation Society «SIAM» has been developing, producing equipment for well research. Over the years, many  [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string TextAboutCompany {
            get {
                return ResourceManager.GetString("TextAboutCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text file with corrections.
        /// </summary>
        public static string TextFileWithCorrections {
            get {
                return ResourceManager.GetString("TextFileWithCorrections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на there are no pressure measurements left.
        /// </summary>
        public static string TherePressureMeasurementsLeft {
            get {
                return ResourceManager.GetString("TherePressureMeasurementsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на thermometer.
        /// </summary>
        public static string Thermometer {
            get {
                return ResourceManager.GetString("Thermometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на time left.
        /// </summary>
        public static string TimeLeft {
            get {
                return ResourceManager.GetString("TimeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на time synchronization.
        /// </summary>
        public static string TimeSynchronization {
            get {
                return ResourceManager.GetString("TimeSynchronization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Destination address.
        /// </summary>
        public static string ToAddress {
            get {
                return ResourceManager.GetString("ToAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total memory:.
        /// </summary>
        public static string TotalMemory {
            get {
                return ResourceManager.GetString("TotalMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trigger permission.
        /// </summary>
        public static string TriggerPermission {
            get {
                return ResourceManager.GetString("TriggerPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на updated.
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The weight of the rods in the upper position, t.
        /// </summary>
        public static string UpperRodWeight {
            get {
                return ResourceManager.GetString("UpperRodWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на USB state:.
        /// </summary>
        public static string USBState {
            get {
                return ResourceManager.GetString("USBState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User name.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Valve test.
        /// </summary>
        public static string ValveTest {
            get {
                return ResourceManager.GetString("ValveTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Various.
        /// </summary>
        public static string Various {
            get {
                return ResourceManager.GetString("Various", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Voltage.
        /// </summary>
        public static string Voltage {
            get {
                return ResourceManager.GetString("Voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на V.
        /// </summary>
        public static string VoltsUnits {
            get {
                return ResourceManager.GetString("VoltsUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field code length exceeds 4 characters. 
        ///DB Siam can&apos;t import the files with the same identifiers..
        /// </summary>
        public static string WarningFieldIdOverflow {
            get {
                return ResourceManager.GetString("WarningFieldIdOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Well.
        /// </summary>
        public static string Well {
            get {
                return ResourceManager.GetString("Well", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the well!.
        /// </summary>
        public static string WellChoiceText {
            get {
                return ResourceManager.GetString("WellChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на with an echogram.
        /// </summary>
        public static string WithAnEchogram {
            get {
                return ResourceManager.GetString("WithAnEchogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrong format or content.
        /// </summary>
        public static string WrongFormatOrContent {
            get {
                return ResourceManager.GetString("WrongFormatOrContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        public static string YesButton {
            get {
                return ResourceManager.GetString("YesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на zero drift.
        /// </summary>
        public static string ZeroDrift {
            get {
                return ResourceManager.GetString("ZeroDrift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Zero drift of the gain channel.
        /// </summary>
        public static string ZeroDriftGainChannel {
            get {
                return ResourceManager.GetString("ZeroDriftGainChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Zeroing sensor.
        /// </summary>
        public static string ZeroingSensor {
            get {
                return ResourceManager.GetString("ZeroingSensor", resourceCulture);
            }
        }
    }
}
