namespace SiamCross.Models.Sensors.Du
{
    public enum DuCommandsEnum
    {
        DeviceType,
        MemoryModelVersion,
        DeviceNameAddress,
        DeviceNameSize,
        DeviceNumber,
        ProgrammVersionAddress,
        ProgrammVersionSize,
        PressureSensitivity,
        PiezoelectricSensitivity,
        PressureZeroOffset,
        PiezoelectricOffset,
        Revbit,
        Voltage,
        Pressure,
        StartMeasurement,
        StartZeroingPressure,
        Initialize,
        StateZeroing,
        SensorOff,
        SensorState,
        ResearchHeader,
        EchogramData,
        DeviceProgrammVersion,
        StubCommand
    }
}
